name: fl_clash
description: Base on FLClash, A Subscription Manager
publish_to: 'none'
version: 0.1.0+20250605
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  characters: ^1.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  path_provider: ^2.1.0
  path: ^1.9.0
  shared_preferences: ^2.5.1
  window_manager: ^0.5.0
  dynamic_color: ^1.7.0
  proxy:
    path: plugins/proxy
  window_ext:
    path: plugins/window_ext
  launch_at_startup: ^0.5.1
  windows_single_instance: ^1.0.1
  json_annotation: ^4.9.0
  file_picker: ^10.1.9
  mobile_scanner: ^7.0.1
  app_links: ^6.4.0
  win32_registry: ^2.0.0
  tray_manager: ^0.5.0
  collection: ^1.18.0
  animations: ^2.0.11
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  freezed_annotation: ^3.0.0
  image_picker: ^1.1.2
  webdav_client: ^1.2.2
  dio: ^5.8.0+1
  win32: ^5.5.1
  ffi: ^2.1.2
  re_editor: ^0.7.0
  re_highlight: ^0.0.3
  archive: ^4.0.7
  lpinyin: ^2.0.3
  emoji_regex: ^0.0.5
  cached_network_image: ^3.4.0
  hotkey_manager: ^0.2.3
  uni_platform: ^0.1.3
  device_info_plus: ^11.3.3
  connectivity_plus: ^6.1.0
  screen_retriever: ^0.2.0
  defer_pointer: ^0.0.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1
  material_color_utilities: ^0.11.1
  flutter_html: ^3.0.0-beta.2
  flag: ^7.0.0
  flutter_svg: ^2.0.10
  fl_chart: ^0.65.0
dev_dependencies:
  intl_utils: ^2.8.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^19.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.13
  args: ^2.4.2
  freezed: ^3.0.6
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  crypto: ^3.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/images/avatars/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: arb
  output_dir: lib/l10n
  template_arb_file: intl_en.arb
  output_localization_file: app_localizations.dart
  output_class_file: app_localizations.dart
  preferred_supported_locales: [en, zh_CN, ja, ru]
  use_deferred_loading: false

ffigen:
  name: "ClashFFI"
  output: 'lib/clash/generated/clash_ffi.dart'
  headers:
    entry-points:
      - 'libclash/android/arm64-v8a/libclash.h'
